# Generated by Django 5.2.4 on 2025-07-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_subjectoffering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectoffering',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='sections',
        ),
    ]
