# Generated by Django 5.2.4 on 2025-07-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dsaclearance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_instructor',
        ),
    ]
