# Generated by Django 5.2.4 on 2025-07-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='account_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Transferee', 'Transferee')], default='Freshman', max_length=10),
        ),
    ]
