# Generated by Django 5.2.4 on 2025-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
